packages:
  - packages/*
  - playground

catalog:
  '@astrojs/mdx': 4.2.6
  '@astrojs/rss': 4.0.11
  '@astrojs/sitemap': 3.3.1
  '@biomejs/biome': 1.9.4
  '@changesets/changelog-github': 0.5.1
  '@changesets/cli': 2.29.2
  '@cloudflare/workers-types': 4.20250507.0
  '@types/node': 22.15.14
  astro: 5.7.11
  async-cache-dedupe: 2.2.0
  knip: 5.54.1
  pkg-pr-new: 0.0.43
  publint: 0.3.12
  tsdown: 0.11.0
  typescript: 5.8.3
  unbuild: 3.5.0
  vite-plugin-mcp: 0.1.2
  wrangler: 4.14.1
  zod: 3.24.4

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - rolldown
  - sharp
  - workerd
