packages:
  - packages/*
  - playground

catalog:
  "@astrojs/mdx": 4.3.1
  "@astrojs/rss": 4.0.12
  "@astrojs/sitemap": 3.5.1
  "@biomejs/biome": 2.2.2
  "@changesets/changelog-github": 0.5.1
  "@changesets/cli": 2.29.6
  "@cloudflare/workers-types": 4.20250831.0
  "@types/node": 22.18.0
  astro: 5.12.3
  async-cache-dedupe: 2.2.0
  knip: 5.63.0
  pkg-pr-new: 0.0.54
  publint: 0.3.12
  tsdown: 0.14.1
  typescript: 5.9.2
  unbuild: 3.6.1
  vite-plugin-mcp: 0.2.4
  wrangler: 4.32.0
  zod: 4.1.5

onlyBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
  - rolldown
  - sharp
  - workerd
