packages:
  - packages/*
  - playground

catalog:
  '@astrojs/mdx': 4.2.3
  '@astrojs/rss': 4.0.11
  '@astrojs/sitemap': 3.3.0
  '@biomejs/biome': 1.9.4
  '@modelcontextprotocol/sdk': 1.9.0
  '@types/node': 22.14.1
  astro: 5.6.1
  knip: 5.50.2
  publint: 0.3.11
  typescript: 5.8.3
  unbuild: 3.5.0

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - sharp
