packages:
  - packages/*
  - playground

catalog:
  "@astrojs/mdx": 4.3.0
  "@astrojs/rss": 4.0.12
  "@astrojs/sitemap": 3.4.0
  "@biomejs/biome": 1.9.4
  "@changesets/changelog-github": 0.5.1
  "@changesets/cli": 2.29.4
  "@cloudflare/workers-types": 4.20250607.0
  "@types/node": 22.15.30
  astro: 5.9.1
  async-cache-dedupe: 2.2.0
  knip: 5.60.2
  pkg-pr-new: 0.0.51
  publint: 0.3.12
  tsdown: 0.12.7
  typescript: 5.8.3
  unbuild: 3.5.0
  vite-plugin-mcp: 0.2.2
  wrangler: 4.19.1
  zod: 3.25.56

onlyBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
  - rolldown
  - sharp
  - workerd
