name: Sync Astro Docs

on:
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install git-restore-mtime
        run: |
          sudo apt-get update
          sudo apt-get install git-restore-mtime

      - name: Clone Astro docs repository
        uses: actions/checkout@v4
        with:
          repository: withastro/docs
          path: astro-docs

      - name: Clone Starlight repository
        uses: actions/checkout@v4
        with:
          repository: withastro/starlight
          path: starlight

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Sync Astro docs
        working-directory: ./astro-docs
        run: |
          git restore-mtime
          cd src/content/docs
          rclone sync en astro-mcp:astro-docs/astro

      - name: Sync Starlight docs
        working-directory: ./starlight
        run: |
          git restore-mtime
          cd docs/src/content/docs
          find . -mindepth 1 -maxdepth 1 -not \( -name "components" -o -name "environmental-impact.md" -o -name "getting-started.mdx" -o -name "guides" -o -name "index.mdx" -o -name "manual-setup.mdx" -o -name "reference" -o -name "resources" \) -print0 | xargs -0 rm -rf
          cd ..
          rclone sync docs astro-mcp:astro-docs/starlight
