name: Sync Astro Docs

on:
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Astro docs repository
        uses: actions/checkout@v4
        with:
          repository: withastro/docs
          path: astro-docs
          fetch-depth: 0

      - name: Restore Git modification time for Astro docs
        working-directory: ./astro-docs
        run: |
          git ls-tree -r --name-only HEAD | while read filename; do
            timestamp=$(git log -1 --format=%at -- "$filename")
            touch -t "$(date -d "@$timestamp" +'%Y%m%d%H%M.%S')" "$filename"
          done
        shell: bash

      - name: Clone Starlight repository
        uses: actions/checkout@v4
        with:
          repository: withastro/starlight
          path: starlight
          fetch-depth: 0

      - name: Restore Git modification time for Starlight
        working-directory: ./starlight
        run: |
          git ls-tree -r --name-only HEAD | while read filename; do
            timestamp=$(git log -1 --format=%at -- "$filename")
            touch -t "$(date -d "@$timestamp" +'%Y%m%d%H%M.%S')" "$filename"
          done
        shell: bash

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: TODO Sync Astro docs
        run: ls -la astro-docs

      - name: TODO Sync Starlight docs
        run: |
          cd starlight/docs/src/content/docs
          find . -mindepth 1 -maxdepth 1 -not \( -name "components" -o -name "environmental-impact.md" -o -name "getting-started.mdx" -o -name "guides" -o -name "index.mdx" -o -name "manual-setup.mdx" -o -name "reference" -o -name "resources" \) -print0 | xargs -0 rm -rf
          cd ..
          rclone sync docs astro-mcp:astro-docs/starlight
